# fly.toml app configuration file generated for restless-mountain-6138 on 2023-10-24T01:43:28+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "restless-mountain-6138"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
internal_port = 8080
protocol      = "tcp"

[[services.ports]]
handlers = ["http"]
port     = 80

[[services.ports]]
handlers = ["tls", "http"]
port     = 443

[[services.http_checks]]
path            = "/health"
method          = "get"
timeout         = "2000"
interval        = "10000"
protocol        = "http"
grace_period    = "5s"
tls_skip_verify = false